#pragma once
int qq_extract();
struct queue;
int struct_queue();
int plalindrome();
struct queue;
struct stack;
int play_card();
int pointer();
int pointer_malloc();
struct node;
int linked();
int linked_insert();
int list_linked();